# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_loader.ipynb.

# %% auto 0
__all__ = ['load_sick_probs', 'load_merit_probs', 'load_exog_info', 'save_best_theta', 'load_best_theta']

# %% ../nbs/01_loader.ipynb 4
import pandas as pd
# import aishiftscheduler.policy as pol #circular import

# %% ../nbs/01_loader.ipynb 5
def load_sick_probs(filename):
  sick_df = pd.read_excel(
      filename,
      sheet_name='SickProbs',
      ## skiprows=3,
      converters={'ResourceId':str}
      )
  return sick_df

# %% ../nbs/01_loader.ipynb 6
def load_merit_probs(filename):
  merit_df = pd.read_excel(
      filename,
      sheet_name='MeritProbs',
      ## skiprows=3,
      converters={'ResourceId':str}
      )
  return merit_df

# %% ../nbs/01_loader.ipynb 7
def load_exog_info(filename):
  exog_info_df = pd.read_excel(
    filename,
    sheet_name='ExogInfo2',
    skiprows=6,
    converters={'volume':int}
    )
  return exog_info_df

# %% ../nbs/01_loader.ipynb 8
def save_best_theta(filename, trn_Best_theta_df):
  trn_Best_theta_df.to_excel(
    filename,
    sheet_name='BestTheta',
  )

# %% ../nbs/01_loader.ipynb 9
def load_best_theta(filename):
  trn_Best_theta_df = pd.read_excel(
    filename,
    sheet_name='BestTheta',
    index_col=0 #None
  )
  trn_Best_theta_tuple = tuple(trn_Best_theta_df.iloc[0])
  return trn_Best_theta_tuple
