# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_config.ipynb.

# %% auto 0
__all__ = ['MODES', 'PATH_shift_scheduler_data', 'PATH_best_theta_data', 'PATH_AIShiftScheduler1', 'SICK_PROBS', 'MERIT_PROBS',
           'EXOG_INFO', 'BEST_THETA_Alloc', 'MAX_RESOURCE_TYPES', 'MAX_RESOURCE_IDS', 'piNAMES', 'thNAMES',
           'BLOCK_START_HOUR', 'SEED_TRAIN', 'SEED_EVALU', 'TH_CumSlots_SPEC', 'TH_SickProb_SPEC', 'TH_CumMerits_SPEC',
           'TH_ContSlots_SPEC', 'TH_Select_SPEC', 'CONTIGUOUS_REWARD', 'GOV_UTIL_THESH']

# %% ../nbs/02_config.ipynb 4
# from collections import namedtuple, defaultdict
# import numpy as np
import pandas as pd
# import matplotlib as mpl
# import matplotlib.pyplot as plt
# from copy import copy
# import time
# import math
# from pprint import pprint
## !pip install -U "ray"
# import ray
# import json

import aishiftscheduler.loader as ldr

# %% ../nbs/02_config.ipynb 6
## PARAMETERS
## MODES:
## TRAIN|LEARN
## EVALU
## INFER|APPLY|SERVE
# MODES = ['LEARN']
# MODES = ['TRAIN', 'EVALU']
MODES = ['TRAIN', 'EVALU', 'INFER']
# MODES = ['EVALU', 'INFER']
# MODES = ['INFER']

# %% ../nbs/02_config.ipynb 8
# based on:
# https://github.com/MannLabs/alphapept/blob/master/nbs/10_constants.ipynb
# https://github.com/MannLabs/alphapept/blob/843de6b7b560b4ebaefdd9fbe533b65098df3b15/alphapept/webui.py#L9
# put data file in 'package' folder (aishiftscheduler), i.e. not in 'nbs' folder
import os
try:
    base = os.path.dirname(os.path.abspath(__file__)) #Cant do this in notebook
except NameError:
    base = os.path.join(os.pardir, 'aishiftscheduler')

if not os.path.isfile(os.path.join(base, "shift_scheduler_data.xlsx")):
    #Calling nbdev build_docs from parent dir
    base = os.path.join(base, 'aishiftscheduler')

# shift_scheduler_data_path = os.path.join(base, "shift_scheduler_data.xlsx")
PATH_shift_scheduler_data = os.path.join(base, "shift_scheduler_data.xlsx"); print(PATH_shift_scheduler_data)
PATH_best_theta_data = os.path.join(base, "best_theta_data.xlsx"); print(PATH_best_theta_data)
PATH_AIShiftScheduler1 = os.path.join(base, "AIShiftScheduler1.png"); print(PATH_AIShiftScheduler1)

# %% ../nbs/02_config.ipynb 10
SICK_PROBS = ldr.load_sick_probs(PATH_shift_scheduler_data)
MERIT_PROBS = ldr.load_merit_probs(PATH_shift_scheduler_data)
EXOG_INFO = ldr.load_exog_info(PATH_shift_scheduler_data)

# %% ../nbs/02_config.ipynb 11
BEST_THETA_Alloc = (0, 0, 0, 1, 'random') #will be written/read eventually

# %% ../nbs/02_config.ipynb 12
MAX_RESOURCE_TYPES = 3
MAX_RESOURCE_IDS = 13

# %% ../nbs/02_config.ipynb 13
piNAMES = ['X__Alloc'] ##policy names
thNAMES = [ ##theta names
  'thCumSlots',
  'thSickProb',
  'thCumMerits',
  'thContSlots',
  'thSelect'
  ## 'thBusyRate' ##later
]
print(f'\n{len(thNAMES)=}')
print(f'{thNAMES=}')

# %% ../nbs/02_config.ipynb 14
BLOCK_START_HOUR = {0: 0, 1: 8, 2:16}

# %% ../nbs/02_config.ipynb 15
SEED_TRAIN = 77777777
SEED_EVALU = 88888888
## N_SAMPLEPATHS = 100; L = N_SAMPLEPATHS
## N_TRANSITIONS = 100; T = N_TRANSITIONS

# %% ../nbs/02_config.ipynb 16
# TH_CumSlots_SPEC = (0, 1, .2)!!!!!!!!!!!!!!!!!!!
TH_CumSlots_SPEC = (0, 1, .5)
# TH_SickProb_SPEC = (0, 1, .2)!!!!!!!!!!!!!!!!!!!!
TH_SickProb_SPEC = (0, 1, .5)
# TH_CumMerits_SPEC = (0, 1, .2)!!!!!!!!!!!!!!!!!!!!!!
TH_CumMerits_SPEC = (0, 1, .5)
# TH_ContSlots_SPEC = (0, 1, .2)!!!!!!!!!!!!!!!!!
TH_ContSlots_SPEC = (0, 1, .5)
## TH_Select_SPEC = ('random', 'ranked_CumMerits')
TH_Select_SPEC = ('random',)
## TH_Select_SPEC = ('ranked_CumMerits',)

# %% ../nbs/02_config.ipynb 18
CONTIGUOUS_REWARD = 1

# %% ../nbs/02_config.ipynb 19
GOV_UTIL_THESH = 0.40
